--- 
title: "Métodos analíticos, ITAM 2021"
author: "Felipe González"
email: felipexgonzalez@gmail.com
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [referencias.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: felipexgonzalez/metodos-analiticos-mcd
description: "Notas para métodos analíticos 2021"
---

# Introducción 

Este curso trata sobre diversas técnicas de análisis de datos, en su mayoría diseñadas
para escalar a datos grandes. El enfoque del curso se concentra más en el entendimiento y 
aplicación de los algoritmos y los métodos, y menos en las herramientas para implementarlos. 

- Vamos a usar Spark en este curso.
    - Python está mejor integrado que R pero R también funciona bien.

## Temario {-}

1. Análisis de conjuntos frecuentes (qué tipo de cosas se suelen comprar juntas?)
    - Algoritmo a-priori
    - Market basket analysis
2. Búsqueda de elementos similares 1
    - Minhashing para documentos
    - Otras notas
        - Pinterest no te quiere estar recomendando lo mismo
        - No hay que repetir el post 
        - ¿Cómo encuentras los datos similares? 
        - Se trata de clustering pero con datos enornes; 
        - Se usa hashing que es una técnica base de las ciencias de la computación
            - Esta es una técnica muy rápida y escalable
3. Búsqueda de elementos similares 2
    - Locality Sensitive Hashing (LSH)
    - Otras notas
        - 
4. Aplicaciones de LSH
    - Joins de similitud aproximados 
5. Conteo probabilístico
    - Algoritmo de Flajolet-Martin
    - Hyperloglog
    - Otras notas
        - Pudes ver elementos únicos.
6. Sistemas de recomendación 1
    - Recomendación por contenido y filtros colaborativos
    - Factorización de matrices y Dimensiones latentes
    - Otras notas
        - Sistemas como los de Netflix o Spotify
7. Reducción de dimensionalidad
    - Descomposición en valores singulares
    - Componentes principales
7. Sistemas de recomendación 2
    - Métodos basados en similitud
    - Mínimos cuadrados alternados
8. Sistemas de recomendación 3 
    - Descenso en gradiente estocástico
    - Sistemas para retroalimentación implícita
9. Análisis de redes 1
    - Medidas de centralidad y pagerank
    - Otras notas
        - Para atacar preguntas como ¿Quién sigue a quién?
10. Análisis de redes 2
    - Clustering y comunidades
11. Modelos de lenguaje 1
    - N-gramas y conteos
    - Aplicaciones
12. Modelos de lenguaje 2
    - Representación de palabras (embeddings)
    - Modelos de redes neuronales
13. Aplicaciones de modelos de lenguaje
    - Corrección de ortografía
    - Reconocimiento de idioma
    - Clasificación de textos
14. Recuperación de información
    - Índices invertidos
    - Modelo de espacio vectorial
    - Normalización y similitud
    - Indexado semántico latente
15. Experimentación y algoritmos de tragamonedas
    - Experimentación y contrafactuales
    - Algoritmos de tragamonedas
    - Tragamonedas bayesianos
    
- Explicación macro de los temas:
    - Similitud
    - Como contar y agrupar eficientemente
    - Sisteas de recomendación
    - Análisis de redes
    - Análisis de texto y lenguaje

- Las notas del curso están R, y en algunos casos usamos python o línea de comandos. Puedes usar python también para hacer tareas y ejercicios. 

- Nuestro texto básico es [@mmd]. Referencias básicas adicionales son
[@jurafsky] (para procesamiento de lenguaje natural), y [sparklyr](https://therinspark.com/) para
utlizar la interfaz de R a [Spark](https://spark.apache.org). 
